--problemstatement3
/* Level-2: Problem 1 - Store Wise Sales Summary
Scenario:
The regional manager wants to analyze total sales generated by each store.
📌 Requirements
1. Display store_name and total sales amount.
2. Calculate total sales using (quantity * list_price * (1 - discount)).
3. Include only completed orders (order_status = 4).
4. Group results by store_name.
5. Sort total sales in descending order.

🛠️ Technical Constraints
- Use INNER JOIN between stores, orders, and order_items tables.
- Use GROUP BY clause.
- Use aggregate functions such as SUM().
- Use WHERE clause for filtering.
- Use ORDER BY clause.

Expectations:
Students must write a grouped query with calculated columns and apply proper filtering.
🎯 Learning Outcome 
Understand GROUP BY, aggregate functions, calculated fields, and filtering grouped data.

 */


CREATE DATABASE StoreSalesDB;

USE StoreSalesDB;




CREATE TABLE Stores
(
    store_id INT PRIMARY KEY IDENTITY(1,1),
    store_name VARCHAR(100)
);

CREATE TABLE Orders
(
    order_id INT PRIMARY KEY IDENTITY(1,1),
    store_id INT,
    order_status INT,

    FOREIGN KEY (store_id) REFERENCES Stores(store_id)
);


CREATE TABLE Order_Items
(
    item_id INT PRIMARY KEY IDENTITY(1,1),
    order_id INT,
    quantity INT,
    list_price DECIMAL(10,2),
    discount DECIMAL(4,2),

    FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);



INSERT INTO Stores (store_name)
VALUES
('Mumbai Store'),
('Pune Store'),
('Delhi Store');

INSERT INTO Orders (store_id, order_status)
VALUES
(1,4),
(1,1),
(2,4),
(3,4),
(2,2);


INSERT INTO Order_Items (order_id, quantity, list_price, discount)
VALUES
(1,2,500,0.10),
(1,1,300,0.05),
(2,3,200,0.00),
(3,5,150,0.20),
(4,1,1000,0.15);




SELECT 
    s.store_name,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_sales
FROM Stores s
INNER JOIN Orders o
ON s.store_id = o.store_id
INNER JOIN Order_Items oi
ON o.order_id = oi.order_id
WHERE o.order_status = 4
GROUP BY s.store_name
ORDER BY total_sales DESC;



--problemstatement4
/* Level-2: Problem 2 - Product Stock and Sales Analysis
Scenario:
The inventory manager wants to compare stock availability and total quantity sold for each product.
📌 Requirements
1. Display product_name, store_name, available stock quantity, and total quantity sold.
2. Include products even if they have not been sold (use appropriate join).
3. Group results by product_name and store_name.
4. Sort results by product_name.
🛠️ Technical Constraints
- Use LEFT JOIN between stocks and order_items.
- Use INNER JOIN with products and stores tables.
- Use GROUP BY clause.
- Use SUM() aggregate function.
- Use ORDER BY clause.
Expectations:
Students should correctly use different join types (INNER and LEFT), grouping, and aggregate functions.
🎯 Learning Outcome 
Develop strong understanding of different JOIN types (INNER, LEFT), aggregation, grouping data, and analyzing relational datasets.
 */


CREATE DATABASE InventoryDB;



USE InventoryDB;






CREATE TABLE Stores
(
    store_id INT PRIMARY KEY IDENTITY(1,1),
    store_name VARCHAR(100)
);


CREATE TABLE Products
(
    product_id INT PRIMARY KEY IDENTITY(1,1),
    product_name VARCHAR(100)
);

-- STOCKS TABLE (PRODUCT STOCK IN EACH STORE)
CREATE TABLE Stocks
(
    stock_id INT PRIMARY KEY IDENTITY(1,1),
    store_id INT,
    product_id INT,
    quantity INT,

    FOREIGN KEY (store_id) REFERENCES Stores(store_id),
    FOREIGN KEY (product_id) REFERENCES Products(product_id)
);

-- ORDER ITEMS TABLE (PRODUCT SALES)
CREATE TABLE Order_Items
(
    item_id INT PRIMARY KEY IDENTITY(1,1),
    product_id INT,
    quantity INT,

    FOREIGN KEY (product_id) REFERENCES Products(product_id)
);




-- INSERT STORES
INSERT INTO Stores (store_name)
VALUES
('Mumbai Store'),
('Pune Store'),
('Delhi Store');

-- INSERT PRODUCTS
INSERT INTO Products (product_name)
VALUES
('Laptop'),
('Mobile'),
('Headphones'),
('Smart Watch');

-- INSERT STOCK DATA
INSERT INTO Stocks (store_id, product_id, quantity)
VALUES
(1,1,50),
(1,2,80),
(2,1,30),
(2,3,60),
(3,4,40);

-- INSERT ORDER ITEMS (SALES DATA)
INSERT INTO Order_Items (product_id, quantity)
VALUES
(1,10),
(1,5),
(2,20),
(3,15);


SELECT 
    p.product_name,
    s.store_name,
    st.quantity AS available_stock,
    SUM(oi.quantity) AS total_quantity_sold
FROM Stocks st
INNER JOIN Products p
ON st.product_id = p.product_id
INNER JOIN Stores s
ON st.store_id = s.store_id
LEFT JOIN Order_Items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name, s.store_name, st.quantity
ORDER BY p.product_name;